dubbo:
    registry:
        protocol: zookeeper
        address: 127.0.0.1:2181
        id: dubbo-registry
    protocol:
        port: 20880
        name: dubbo
        id: dubbo
    application:
        name: dubbo-consumer
        id: dubbo-consumer
        qosEnable: true
        qosPort: 22224
