
dubbo:
    registry:
        address: nacos://nacos:8848
    protocol:
        port: 20880
        name: dubbo
    application:
        name: ${spring.application.name}
        qosEnable: true
        qos-accept-foreign-ip: false
